name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy to S3
      run: aws s3 sync build/web/ s3://flutterwebdemo
      continue-on-error: true

    - name: Check deployment status
      run: |
       # Verify deployment by checking if files are in S3 bucket
        if aws s3 ls s3://flutterwebdemo; then
          echo "Deployment successful"
        else
          echo "Deployment failed"
          exit 1
        fi
